version: '3.8'

services:
  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: R1234r
      MYSQL_USER: clarusway
      MYSQL_PASSWORD: Clarusway_1
      MYSQL_DATABASE: bookstore_db
    networks:
      - mynetwork

  server:
    image: mfaktas/bookstore-api:latest
    restart: always
    depends_on:
      - database
    ports:
      - "80:80"
    networks:
      - mynetwork



networks:
  mynetwork:
    driver: bridge
